### ISSUE TITLE
Uncaught (in promise) TypeError: undefined is not a valid argument for URI

### ISSUE THREAD

**Issue by hanumantgawali** [painty/CSS-Used-ChromeExt#11]
I am using on local host its showing error Uncaught (in promise) TypeError: undefined is not a valid argument for URI .. in url.js

**Comment by painty** [comment]
So, how can I reproduce the error?

**Comment by hanumantgawali** [comment]
[surgical](https://www.ihealthmantra.com/surgical) this is a link where you can observe bug.

**Comment by painty** [comment]
Fixed in 2.2.8 .
