### ISSUE TITLE
local preview HTML not rendering correctly.

### ISSUE THREAD

**Issue by emmastone9** [painty/CSS-Used-ChromeExt#12]
1. The url of page inspected.

`https://www.reuters.com/article/us-soccer-fifa/soccer-fifa-proposes-staging-a-new-mini-world-cup-every-two-years-idUSKBN1I31AL`

2. In chrome dev tools, select <html lang

3. Click on Local Preview
Copy the HTML that opens in about:blank by open dev tools and copying the entire HTML tag.

4. Actual result.
The copied HTML renders differently than the one in `Local Preview`. Any idea what might be causing this?

**Comment by painty** [comment]
Can your provide a screenshot ?

**Comment by emmastone9** [comment]
The error was related to fonts not loaded correctly aka CORS issue; fixed it and now its rendering correctly.
Thank you.
