### ISSUE TITLE
No CSS is displayed....

### ISSUE THREAD

**Issue by ThisIsMyFavouriteJar** [painty/CSS-Used-ChromeExt#13]
1. The url of page inspected.

Any page I tried...

2. The element inspected.

Any element I tried ....

3. Expected result.

See some CSS

4. Actual result.

See the following:
1. Reload the inspected page
2. Reopen the Devtool
3. Select an elements on the left

(Even when reloading or restarting Chrome.)

**Comment by painty** [comment]
Is there any error message in the console?
And can you provide your Chrome version and platform?

**Comment by Chris2011** [comment]
Same here;
Chrome:  68.0.3440.106
Windows 10 64 Bit.

**Comment by AykutCanturk** [comment]
Same problem. Looks like preview option is working right even it shows no css for selected tag, any tag. Not for all sites but I suspect the ones developed by aspnet webforms. on same page it works for some elements like menus but not works for some elements like "some" labels. I suspect it has something to do with span elements with id lie "contentplaceholder.....xxxxx"

**Comment by Rigent** [comment]
I have the same issue. I have changed the permissions as requested, refreshed the page and now only see:
"on Navigated.
Select another dom on the left 
or
Reopen the Devtool"

This happens with pure HTML page and a linked CSS CDN (bootstrap). I have restarted the browser and made changes to the page.

Chrome version 75.0.3770.100
Windows 10 64bit

**Comment by faridchaouki** [comment]
SOLVED!
You need to upgrade the permissions of the plugin to "On all sites" other wise it cannot access any CSS from a different domain that the current page.
![Site access](https://user-images.githubusercontent.com/1260257/92261581-a39ac600-eea7-11ea-9e47-19bef433765d.jpg)

**Comment by painty** [comment]
It has been a long time since last release. Check if it can be reproduced on the latest version.

**Comment by gwenm** [comment]
Does not work on any site..Even with all sites enabled.

Edit : I thought it wasn't working and then I reloaded the page and the css appeared.

**Comment by imartov** [comment]
Yes, the solution is:
1. choose block / element
2. reload page
