### ISSUE TITLE
Element Preview doen't work on new Chrome.

### ISSUE THREAD

**Issue by Vortelf** [painty/CSS-Used-ChromeExt#15]
Since latest chrome update - 69.0.3497.100 - local preview doesn't work. Probably some changes in the API. Codepen still works fine, so it's not a big deal, but still

**Comment by painty** [comment]
[V2.2.11](https://chrome.google.com/webstore/detail/css-used/cdopjfddjlonogibjahpnmjpoangjfff) should have solved this.
Thanks @NamPNQ #16
