### ISSUE TITLE
Parsing won't work on my website

### ISSUE THREAD

**Issue by JimmyFarcy** [painty/CSS-Used-ChromeExt#22]
Hi, 

First i must say that i used your awesome plugin for sometimes. I came across a bug on your code that is happening during the parsing of the css. My css is all compiled into on app.css.

Here is the erreur that i get inside the console:

![screen-shot](https://user-images.githubusercontent.com/6976242/53027279-ed0df680-3464-11e9-953c-1406e8b9ac83.png)

I'm on Chrome Version 70.0.3538.102 (Official build) (64 bits)

**Comment by EduVencovsky** [comment]
I have the same problem, I'm using `scss` with webpack on a react application. It have `modules: true` (not sure if this changes something)

**Comment by painty** [comment]
Can you give me an online example so I can reproduce this issue ?

**Comment by painty** [comment]
> 



> I have the same problem, I'm using `scss` with webpack on a react application. It have `modules: true` (not sure if this changes something). Also, maybe because of the source map, it can't read the `scss`?

only the compiled native css is supported, so no `scss`.
