### ISSUE TITLE
Navigational links no longer working

### ISSUE THREAD

**Issue by Weramac** [painty/CSS-Used-ChromeExt#23]
1. The url of page inspected.

https://www.vappingo.com/Proofreading-Services/Dissertation-Proofreading/

When I used the CSS Used tool, the code selected created a page that displays perfectly. However, the navigational links no longer work. In the code preview, they do work; however, on the live site, they are inactive.

Do you know what is causing this?

**Comment by painty** [comment]
Sorry I'm not an English native speaker. What does " live site" refer to and what does "inactive" mean ?
FYI, the preview page filters out scripts, just a static look with css.

**Comment by Weramac** [comment]
Hi,

By "live site" I mean the site that is online. After copy and pasting the generated css code, the links on the navigation bar no longer work (they were functional before the css code change).

For example, on the following page: https://www.vappingo.com/Proofreading-Services/Dissertation-Proofreading/

None of the links at the top ("Home", "Services", "Prices", etc.) work when clicked.

**Comment by painty** [comment]
It's not caused by the extension. 
eg. You can try firefox or uninstall the extension, but problem still exists.

**Comment by Weramac** [comment]
Hi,

What I am trying to say is that the css code selected by the extension is missing something out. As a result, the navigational links don’t work. I’m trying to work out what is missing from the css code generated by the extension so that I can fix the issue.
