### ISSUE TITLE
extension stuck in parsing css

### ISSUE THREAD

**Issue by emmastone9** [painty/CSS-Used-ChromeExt#24]
1. The url of page inspected.

`https://www.bighammerwines.com/products/2016-nesios-cabernet-sangiovese-igt`

2. The element inspected.

`<html lang`

3. Expected result.

```css
local preview should show the css
```

4. Actual result.

```css
stuck in parsing
![image](https://user-images.githubusercontent.com/34253759/59971810-3ae05b80-9538-11e9-80c8-f469f840016f.png)

```

**Comment by painty** [comment]
Will be fixed in v 2.4.2 dde2bfb2dd1e767bd9321f7326547ccf6502efda
