### ISSUE TITLE
Can't parse google.com SERP

### ISSUE THREAD

**Issue by davidsgrogan** [painty/CSS-Used-ChromeExt#25]
1. The url of page inspected.

`https://www.google.com/search?q=dogs`

2. The element inspected.

`#rso > div:nth-child(3) > div > div:nth-child(1) > div > div > div.s` But I haven't had success with any element.

3. Expected result.

Some CSS!

4. Actual result.

> For the first time installed/updated/allowedFileAccess:
> Refresh the inspected page
> Reopen the Devtool or Select another elements on the left
> If problem persists, please create an issue.

I've tried refreshing and reopening devtools. The console is empty.

**Comment by painty** [comment]
It has been a long time since last release. v3.0.0 is now available [on the webstore](https://chrome.google.com/webstore/detail/cdopjfddjlonogibjahpnmjpoangjfff), with lots of improvement, give it a try. #53 Looking forward to your feedback.
