### ISSUE TITLE
doesn't seem to like local files (file:///)

### ISSUE THREAD

**Issue by end-user** [painty/CSS-Used-ChromeExt#28]
1. The url of page inspected.

copy an html file and open it in chrome - of course it needs some on-page css

2. The element inspected.

any

3. Expected result.

'css used' should have current, live rules with any non-relevant selectors stripped out

4. Actual result.

'css used' has no rules available; says select another dom on the left or reopen the devtool.

**Comment by end-user** [comment]
nevermind - I see that there's a permission setting for the extension to allow access to file urls

**Comment by MaxwellGriffin** [comment]
I'm still getting this same issue with local files. I have the "Allow access to file URLs" option enabled in the extension settings. I set up a local server with XAMPP and I was then able to use the extension.

**Comment by painty** [comment]
> I also have this issue the console shows: CSS-Used: Fail to get: file:///home/amasidlover/workspace/zymonic-dev/stylesheets/ZymonicDefault.css Even with the 'file urls' permission enabled for the extension.

Should have been fixed in the recently released version v3.0.0
