### ISSUE TITLE
RTL & Responsive Problem

### ISSUE THREAD

**Issue by danytop** [painty/CSS-Used-ChromeExt#30]
Hello 
Thanks for this amazing tool
But i have two serious problem.
this is my site: https://danialtaherifar.ir
when i used this css code , header section direction changed to LTR instead RTL and Rearranged objects in header.
also Responsive layout not work. 
can u help me for resolve this problems?and improve this great tool?
Thanks

**Comment by painty** [comment]
Q1: The dir attribute, which specifies the text direction of the element's contentis , is on the html tag . You can think of it as an inherited style. So just manualy set it on your target page. 

Q2:Need more info.
