### ISSUE TITLE
Inconsistent layout when copy/paste HTML and CSS from codepen.

### ISSUE THREAD

**Issue by emmastone9** [painty/CSS-Used-ChromeExt#32]
1. The url of page inspected.

`https://www.iheartraves.com/blogs/post/10-festival-camping-tips`

2. The element inspected.

`html`

3. Expected result.

Banner logo should be in the center

4. Actual result.

CodePen preview shows the banner logo in center, however, when I copy paste the codepen HTML and CSS, the banner logo in a text file, the banner logo layout is off.
Any idea why the logo might be off? I compared the file contents, and they look the same.

**Comment by emmastone9** [comment]
@painty @NamPNQ : any pointers on what might be the issue?

**Comment by NamPNQ** [comment]
You can try to use `save` feature in codepen, maybe you copy-paste missing something

**Comment by emmastone9** [comment]
thx @NamPNQ . The issue was related to height in CSS, i replaced it with 100% and that resolved the issue.
