### ISSUE TITLE
Doesn't work on reddit

### ISSUE THREAD

**Issue by nmaxcom** [painty/CSS-Used-ChromeExt#4]
I haven't tried it a lot, here in github seems to work okay. I'm trying in reddit, to extract the CSS related to the ".md" class there for a Mark Down previewer but I get this:

![image](https://user-images.githubusercontent.com/8936090/29849266-ea3a3f0a-8d25-11e7-9c21-74319d9db725.png)

I noticed the console complained at the same time:

![image](https://user-images.githubusercontent.com/8936090/29849278-f9d120be-8d25-11e7-87f9-079bbbca932e.png)

But when I click to see that code it loads nothing 😕 

![image](https://user-images.githubusercontent.com/8936090/29849294-164b7442-8d26-11e7-9be7-6a50485213a7.png)

**Comment by painty** [comment]
Fixed and update will be on Chrome Store soon.
