### ISSUE TITLE
Can't copy label css from google Graph APi

### ISSUE THREAD

**Issue by SebCCare** [painty/CSS-Used-ChromeExt#7]
Example:

It should gather inline style also.
`<text x="0" y="15" style="cursor: default; user-select: none; -webkit-font-smoothing: antialiased; font-family: Roboto; font-size: 16px;" fill="#757575" dx="0px">Percentage occupancy</text>`

**Comment by painty** [comment]
Inline style is bonded to html. You should copy the html as well.
